In [25]:
import sqlite3
import pandas as pd

# Create database
conn = sqlite3.connect("grocchat.db")

# Load CSV file
df = pd.read_csv("final_dataset.csv")

# Preview data
df.head()

,product_id,product_name,supplier_id,supplier_name,stock_left,last_time_ordered_date,received_date,sale_volume_previous_month,status,reorder_level,unit_price_usd,category,supplier_lead_time_days,expiry_date,sales_week1,sales_week2,sales_week3,sales_week4
0,PROD001,Lakshmi Sooji 4lb,S004,Oil India Traders,81,2/22/2026,3/3/2026,993,active,77,3.25,General,9,4/9/2026,179,196,262,356
1,PROD002,MDH Sooji 4lb,S002,Spice World India,121,2/20/2026,2/21/2026,1077,active,177,3.40,General,1,4/6/2026,324,301,179,273
2,PROD003,Patanjali Sooji 4lb,S004,Oil India Traders,239,2/26/2026,2/27/2026,1196,active,157,3.10,General,1,3/30/2026,272,314,395,215
3,PROD004,Bikaji Sooji 4lb,S005,Haldiram Distributors,89,2/25/2026,3/3/2026,557,active,161,3.55,General,6,4/20/2026,107,154,135,161
4,PROD005,Deep Besan 4lb,S008,MTR Ready Mix,284,2/13/2026,2/15/2026,915,active,162,3.35,General,2,3/6/2026,216,194,217,288

In [26]:
df.to_sql("inventory", conn, if_exists="replace", index=False)

print("Data stored in database!")

Data stored in database!

In [27]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [28]:
pd.read_sql("SELECT * FROM inventory LIMIT 5", conn)

,product_id,product_name,supplier_id,supplier_name,stock_left,last_time_ordered_date,received_date,sale_volume_previous_month,status,reorder_level,unit_price_usd,category,supplier_lead_time_days,expiry_date,sales_week1,sales_week2,sales_week3,sales_week4
0,PROD001,Lakshmi Sooji 4lb,S004,Oil India Traders,81,2/22/2026,3/3/2026,993,active,77,3.25,General,9,4/9/2026,179,196,262,356
1,PROD002,MDH Sooji 4lb,S002,Spice World India,121,2/20/2026,2/21/2026,1077,active,177,3.40,General,1,4/6/2026,324,301,179,273
2,PROD003,Patanjali Sooji 4lb,S004,Oil India Traders,239,2/26/2026,2/27/2026,1196,active,157,3.10,General,1,3/30/2026,272,314,395,215
3,PROD004,Bikaji Sooji 4lb,S005,Haldiram Distributors,89,2/25/2026,3/3/2026,557,active,161,3.55,General,6,4/20/2026,107,154,135,161
4,PROD005,Deep Besan 4lb,S008,MTR Ready Mix,284,2/13/2026,2/15/2026,915,active,162,3.35,General,2,3/6/2026,216,194,217,288

In [29]:
pd.read_sql("""
SELECT product_name, stock_left, reorder_level
FROM inventory
WHERE stock_left < reorder_level
""", conn)

              product_name  stock_left  reorder_level
0            MDH Sooji 4lb         121            177
1         Bikaji Sooji 4lb          89            161
2      Pillsbury Besan 4lb         108            129
3        Lakshmi Atta 10lb          43            187
4          Konark Ghee 4lb         122            154
5            ITC Rajma 4lb          94            194
6           Tata Rajma 4lb         107            150
7     Konark Moong Dal 4lb          44             80
8   Lakshmi Masoor Dal 4lb         114            146
9         MTR Idli Mix 2lb          75             96
10  Bikaji Namkeen Mix 1lb         124            141
11     Haldiram Bhujia 1lb          32            120
12    Everest Urad Dal 4lb         100            101
13       Deep Toor Dal 4lb          23            188
14          Deep Atta 10lb          16            187
15       Lakshmi Sooji 4lb         123            191
16        MDH Idli Mix 2lb         180            196
17       Everest Rajma 4lb          28            173
18      Everest Bhujia 1lb         114            194

In [30]:
!pip install openai

Requirement already satisfied: openai in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.30.0)
Requirement already satisfied: anyio<5,>=3.5.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openai) (2.12.5)
Requirement already satisfied: sniffio in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: colorama in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tqdm>4->openai) (0.4.6)

In [31]:
from openai import AzureOpenAI

client = AzureOpenAI(
    api_key="FNos7JA0VT6gvlwHsc0VE71d5KZCy6JzAou519avDPaVKU4qrfcgJQQJ99CDACfhMk5XJ3w3AAAAACOGFeQF",
    api_version="2024-12-01-preview",
    azure_endpoint="https://grocchaatt-resource.cognitiveservices.azure.com/"
)

In [32]:
response = client.chat.completions.create(
    model="gpt-4o-mini",  # your deployment name
    messages=[{"role": "user", "content": "Say hello"}]
)

print(response.choices[0].message.content)

Hello! How can I assist you today?

In [33]:
schema = """
Table: inventory

Columns:
product_id
product_name
supplier_id
supplier_name
stock_left
reorder_level
sale_volume_previous_week
sale_volume_previous_month
expiry_date
category
supplier_lead_time_days
sales_week1
sales_week2
sales_week3
sales_week4
"""

In [34]:
def generate_sql(question):

    prompt = f"""
You are a SQL assistant.

Database schema:
{schema}

Rules:
- Use only the inventory table
- Generate only SELECT queries
- Do not modify the database
- Return only SQL (no explanation)

IMPORTANT:
- expiry_date is stored as DATE
- Use SQLite date functions
- To filter by month, use: strftime('%m', expiry_date)

User Question:
{question}
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content

In [35]:
def clean_sql(sql_query):
    return sql_query.replace("```sql", "").replace("```", "").strip()


def run_sql(sql_query):
    sql_query = clean_sql(sql_query)

    print("Generated SQL:")
    print(sql_query)

    if not sql_query.lower().startswith("select"):
        print("Only SELECT queries allowed")
        return None

    return pd.read_sql(sql_query, conn)

In [36]:
df['expiry_date'] = pd.to_datetime(df['expiry_date'])
df['expiry_date'] = df['expiry_date'].dt.strftime('%Y-%m-%d')

df.to_sql("inventory", conn, if_exists="replace", index=False)

100

In [37]:
!pip install faiss-cpu sentence-transformers
!pip install ipywidgets

Requirement already satisfied: faiss-cpu in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.13.2)
Requirement already satisfied: sentence-transformers in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (5.3.0)
Requirement already satisfied: numpy<3.0,>=1.25.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from faiss-cpu) (2.4.4)
Requirement already satisfied: packaging in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from faiss-cpu) (26.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (5.5.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (1.9.0)
Requirement already satisfied: torch>=1.11.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (2.11.0)
Requirement already satisfied: scikit-learn in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: scipy in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: setuptools<82 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: click>=8.2.1 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Requirement already satisfied: ipywidgets in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (8.1.8)
Requirement already satisfied: comm>=0.1.3 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipywidgets) (9.12.0)
Requirement already satisfied: traitlets>=4.3.1 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.6)
Requirement already satisfied: executing>=1.2.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\nutan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)

In [38]:
promotion_chunks = [
    "Offer discounts for near expiry products to reduce loss",
    "Bundle slow-moving items with fast-selling products",
    "Apply small discounts for high demand products to maintain margin",
    "Use higher discounts for low demand products to clear inventory",
    "Promote sweets and snacks during festival seasons",
    "Use limited-time offers to create urgency",
    "Place high demand items at visible locations to increase sales"
]

In [39]:
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

embeddings = model.encode(promotion_chunks)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [40]:
dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings))

In [41]:
def retrieve_knowledge(query, k=3):

    query_embedding = model.encode([query])
    
    distances, indices = index.search(np.array(query_embedding), k)
    
    results = [promotion_chunks[i] for i in indices[0]]
    
    return "\n".join(results)

In [42]:
def decision_engine(df):

    decisions = []

    for _, row in df.iterrows():

        # 🔴 Low stock
        if 'stock_left' in df.columns and 'reorder_level' in df.columns:
            if row['stock_left'] < row['reorder_level']:
                decisions.append(f"Restock {row['product_name']} (low stock)")

        # 🟡 Expiry logic (only if column exists)
        if 'expiry_date' in df.columns:
            if pd.to_datetime(row['expiry_date']) <= pd.Timestamp.today() + pd.Timedelta(days=7):
                decisions.append(f"Apply discount on {row['product_name']} (expiring soon)")

        # 📈 Trend logic
        if 'sales_week1' in df.columns and 'sales_week4' in df.columns:
            trend = row['sales_week4'] - row['sales_week1']
            if trend > 10:
                decisions.append(f"Increase stock for {row['product_name']} (demand rising)")

    return decisions

In [43]:
def explain_decisions(df, decisions, question):

    relevant_knowledge = retrieve_knowledge(question)
    data_summary = df.to_string(index=False)

    prompt = f"""
You are an AI assistant for a grocery store owner.

DATA:
{data_summary}

DECISIONS:
{decisions}

RELEVANT KNOWLEDGE:
{relevant_knowledge}

Instructions:
- Be concise and business-focused
- No generic advice
- Use ONLY the provided data
- Group products logically (high demand, low demand, expiring)
- Suggest realistic actions (discount %, bundling, etc.)
- Maximum 5 bullet points total
- Write like a store advisor

Output format:

📊 Key Insights:
- ...

📌 Recommended Actions:
- ...
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content

In [44]:
def ask_ai(question):

    # Step 1: Generate SQL
    sql_query = generate_sql(question)

    # Step 2: Run SQL
    result = run_sql(sql_query)

    if result is None or result.empty:
        print("No data found")
        return

    # Step 3: Show data
    print("\nData:")
    display(result)

    # Step 4: Create decisions (IMPORTANT)
    decisions = decision_engine(result)

    print("\nRaw Decisions:")
    for d in decisions:
        print(d)

    # Step 5: Explanation (FIXED)
    explanation = explain_decisions(result, decisions, question)

    print("\nAI Explanation:")
    print(explanation)

In [45]:
ask_ai("which products will expire in april?")

Generated SQL:
SELECT *
FROM inventory
WHERE strftime('%m', expiry_date) = '04';

Data:

,product_id,product_name,supplier_id,supplier_name,stock_left,last_time_ordered_date,received_date,sale_volume_previous_month,status,reorder_level,unit_price_usd,category,supplier_lead_time_days,expiry_date,sales_week1,sales_week2,sales_week3,sales_week4
0,PROD001,Lakshmi Sooji 4lb,S004,Oil India Traders,81,2/22/2026,3/3/2026,993,active,77,3.25,General,9,2026-04-09,179,196,262,356
1,PROD002,MDH Sooji 4lb,S002,Spice World India,121,2/20/2026,2/21/2026,1077,active,177,3.40,General,1,2026-04-06,324,301,179,273
2,PROD004,Bikaji Sooji 4lb,S005,Haldiram Distributors,89,2/25/2026,3/3/2026,557,active,161,3.55,General,6,2026-04-20,107,154,135,161
3,PROD006,Pillsbury Besan 4lb,S010,Deep Foods Ltd,108,2/2/2026,2/6/2026,1143,active,129,3.80,General,4,2026-04-02,238,229,249,427
4,PROD011,Lakshmi Urad Dal 4lb,S004,Oil India Traders,391,2/9/2026,2/19/2026,1335,active,126,3.10,Pulses,10,2026-04-13,466,210,215,444
5,PROD012,Everest Urad Dal 4lb,S003,Dal Masters Pvt Ltd,270,2/25/2026,2/26/2026,1293,active,110,3.35,Pulses,1,2026-04-07,312,339,382,260
6,PROD015,MTR Toor Dal 4lb,S001,Rajesh Grocery Suppliers,498,2/24/2026,3/1/2026,622,active,97,3.25,Pulses,5,2026-04-18,186,154,124,158
7,PROD018,Bikaji Mustard Oil 5liter,S002,Spice World India,384,2/3/2026,2/12/2026,1220,active,191,22.00,Cooking Oil,9,2026-04-08,421,284,361,154
8,PROD019,Lakshmi Ghee 4lb,S004,Oil India Traders,485,2/24/2026,2/28/2026,1349,active,165,48.00,General,4,2026-04-21,397,457,225,270
9,PROD021,Konark Ghee 4lb,S010,Deep Foods Ltd,122,2/23/2026,2/24/2026,700,active,154,47.80,General,1,2026-04-09,125,138,205,232
10,PROD026,Tata Tea Leaves 1lb,S001,Rajesh Grocery Suppliers,343,3/4/2026,3/6/2026,1150,active,194,9.50,General,2,2026-04-18,376,269,228,277
11,PROD027,ITC Rajma 4lb,S001,Rajesh Grocery Suppliers,94,2/13/2026,2/18/2026,1070,active,194,3.80,General,5,2026-04-08,202,208,171,489
12,PROD029,Bikaji Chana 4lb,S010,Deep Foods Ltd,254,2/28/2026,3/9/2026,632,active,90,3.15,General,9,2026-04-17,165,207,137,123
13,PROD031,Lakshmi Masoor Dal 4lb,S005,Haldiram Distributors,114,2/11/2026,2/15/2026,976,active,146,3.05,Pulses,4,2026-04-07,186,250,225,315
14,PROD032,Haldiram Masoor Dal 4lb,S008,MTR Ready Mix,171,2/28/2026,3/1/2026,651,active,95,3.25,Pulses,1,2026-04-26,185,137,167,162
15,PROD033,Everest Masoor Dal 4lb,S002,Spice World India,285,2/9/2026,2/12/2026,727,active,164,3.15,Pulses,3,2026-04-04,143,222,250,112
16,PROD034,Pillsbury Poha 4lb,S009,Konark Enterprises,370,2/26/2026,3/7/2026,167,active,146,3.00,General,9,2026-04-25,47,57,40,23
17,PROD035,Patanjali Poha 4lb,S002,Spice World India,490,2/16/2026,2/18/2026,229,active,139,2.90,General,2,2026-04-06,48,41,43,97
18,PROD038,Haldiram Papad 200pcs,S003,Dal Masters Pvt Ltd,389,2/23/2026,3/2/2026,1070,active,108,5.25,General,7,2026-04-03,177,301,276,316
19,PROD044,Tata Sambar Powder 1lb,S009,Konark Enterprises,179,2/25/2026,3/2/2026,385,active,137,5.80,General,5,2026-04-12,83,61,118,123
20,PROD045,Mother's Recipe Mango Pickle 2lb jar,S010,Deep Foods Ltd,232,2/26/2026,3/4/2026,636,active,99,8.50,General,6,2026-04-20,213,175,201,47
21,PROD049,Patanjali Sunflower Oil 5liter,S010,Deep Foods Ltd,301,2/18/2026,2/19/2026,811,active,180,20.50,Cooking Oil,1,2026-04-11,216,134,226,235
22,PROD057,Patanjali Tea Leaves 1lb,S005,Haldiram Distributors,402,2/16/2026,2/20/2026,781,active,143,9.00,General,4,2026-04-11,193,132,175,281
23,PROD058,MDH Vermicelli 2lb,S006,Everest Spices Co.,173,2/27/2026,3/2/2026,654,active,109,4.10,General,3,2026-04-22,178,131,195,150
24,PROD059,Lakshmi Ghee 4lb,S007,Aashirvaad Foods,218,2/15/2026,2/22/2026,563,active,177,47.50,General,7,2026-04-19,151,95,150,167
25,PROD060,Deep Masoor Dal 4lb,S001,Rajesh Grocery Suppliers,448,2/8/2026,2/16/2026,506,active,146,3.20,Pulses,8,2026-04-08,112,169,177,48
26,PROD064,Lakshmi Mustard Oil 5liter,S005,Haldiram Distributors,204,2/15/2026,2/21/2026,845,active,167,22.20,Cooking Oil,6,2026-04-07,234,256,208,147
27,PROD069,Deep Rajma 4lb,S007,Aashirvaad Foods,213,2/20/2026,2/22/2026,1106,active,132,3.65,General,2,2026-04-05,352,175,314,265
28,PROD072,Everest Toor Dal 4lb,S003,Dal Masters Pvt Ltd,385,2/21/2026,2/26/2026,1130,active,193,3.55,Pulses,5,2026-04-09,346,323,180,281
29,PROD074,Deep Papad 200pcs,S010,Deep Foods Ltd,352,2/1/2026,2/9/2026,1371,active,194,5.45,General,8,2026-04-09,342,215,473,341
30,PROD078,Deep Namkeen Mix 1lb,S006,Everest Spices Co.,227,2/11/2026,2/17/2026,1219,active,148,5.60,General,6,2026-04-09,411,186,268,354
31,PROD087,Patanjali Ghee 4lb,S005,Haldiram Distributors,348,2/8/2026,2/11/2026,1065,active,70,46.90,General,3,2026-04-08,233,234,334,264
32,PROD089,Patanjali Atta 10lb,S005,Haldiram Distributors,413,2/19/2026,2/23/2026,935,active,127,14.60,General,4,2026-04-23,278,298,304,55
33,PROD092,Deep Atta 10lb,S001,Rajesh Grocery Suppliers,465,2/11/2026,2/21/2026,756,active,128,14.40,General,10,2026-04-12,158,161,146,291
34,PROD099,Lakshmi Urad Dal 4lb,S010,Deep Foods Ltd,419,2/6/2026,2/11/2026,1064,active,174,3.28,Pulses,5,2026-04-05,346,187,180,351

Raw Decisions:
Apply discount on Lakshmi Sooji 4lb (expiring soon)
Increase stock for Lakshmi Sooji 4lb (demand rising)
Restock MDH Sooji 4lb (low stock)
Apply discount on MDH Sooji 4lb (expiring soon)
Restock Bikaji Sooji 4lb (low stock)
Increase stock for Bikaji Sooji 4lb (demand rising)
Restock Pillsbury Besan 4lb (low stock)
Apply discount on Pillsbury Besan 4lb (expiring soon)
Increase stock for Pillsbury Besan 4lb (demand rising)
Apply discount on Everest Urad Dal 4lb (expiring soon)
Apply discount on Bikaji Mustard Oil 5liter (expiring soon)
Restock Konark Ghee 4lb (low stock)
Apply discount on Konark Ghee 4lb (expiring soon)
Increase stock for Konark Ghee 4lb (demand rising)
Restock ITC Rajma 4lb (low stock)
Apply discount on ITC Rajma 4lb (expiring soon)
Increase stock for ITC Rajma 4lb (demand rising)
Restock Lakshmi Masoor Dal 4lb (low stock)
Apply discount on Lakshmi Masoor Dal 4lb (expiring soon)
Increase stock for Lakshmi Masoor Dal 4lb (demand rising)
Apply discount on Everest Masoor Dal 4lb (expiring soon)
Apply discount on Patanjali Poha 4lb (expiring soon)
Increase stock for Patanjali Poha 4lb (demand rising)
Apply discount on Haldiram Papad 200pcs (expiring soon)
Increase stock for Haldiram Papad 200pcs (demand rising)
Increase stock for Tata Sambar Powder 1lb (demand rising)
Apply discount on Patanjali Sunflower Oil 5liter (expiring soon)
Increase stock for Patanjali Sunflower Oil 5liter (demand rising)
Apply discount on Patanjali Tea Leaves 1lb (expiring soon)
Increase stock for Patanjali Tea Leaves 1lb (demand rising)
Increase stock for Lakshmi Ghee 4lb (demand rising)
Apply discount on Deep Masoor Dal 4lb (expiring soon)
Apply discount on Lakshmi Mustard Oil 5liter (expiring soon)
Apply discount on Deep Rajma 4lb (expiring soon)
Apply discount on Everest Toor Dal 4lb (expiring soon)
Apply discount on Deep Papad 200pcs (expiring soon)
Apply discount on Deep Namkeen Mix 1lb (expiring soon)
Apply discount on Patanjali Ghee 4lb (expiring soon)
Increase stock for Patanjali Ghee 4lb (demand rising)
Increase stock for Deep Atta 10lb (demand rising)
Apply discount on Lakshmi Urad Dal 4lb (expiring soon)

AI Explanation:
📊 Key Insights:
- Several products are experiencing a surge in demand while others are nearing their expiry dates.
- High-demand items like Lakshmi Sooji 4lb and Pillsbury Besan 4lb need increased stock due to rising sales.
- Products like MDH Sooji 4lb, Haldiram Papad 200pcs, and Patanjali Ghee 4lb show low stock but maintain consistent sales volumes.

📌 Recommended Actions:
- Apply a **15% discount** on all expiring products such as Lakshmi Sooji 4lb, MDH Sooji 4lb, and Pillsbury Besan 4lb to clear inventory and mitigate losses.
- Increase stock for high-demand items: Lakshmi Sooji 4lb, Pillsbury Besan 4lb, and Lakshmi Ghee 4lb by **20%** based on their sales trajectory.
- Bundle slow-moving items like Patanjali Poha 4lb with fast-selling products like Lakshmi Urad Dal 4lb to incentivize sales.
- Restock essential items like MDH Sooji 4lb and ITC Rajma 4lb immediately to prevent stockouts.
- Monitor expiring Ghee and oil products, applying a **10% discount** to induce sales while maintaining stock levels.